### ISSUE TITLE
Consider using semver for version tags

### ISSUE THREAD

**Issue by brianlheim** [madskjeldgaard/mkplugins#12]
Right now the release tags mostly follow the pattern x.y.zA where A is an incrementing letter. First, I'd like to ask what the purpose for this extra letter is (why do this instead of increment the patch version?). Second, I'd like to ask you to consider using https://semver.org/ instead, since this is a widely-used and well-regarded versioning scheme.

**Comment by madskjeldgaard** [comment]
I agree with this. You don't want to know the honest, embarassing truth about why the letters snuck in there in the version numbering, haha!Aand I know from experience how annoying inconsistent version naming can be for packagers on the other end so I'll adopt this !

**Comment by brianlheim** [comment]
sounds good! btw, if the letters are just there to test your CI deployment (i'm guessing that's what you're referring to?) you could label them like `x.y.z-rcN` where N is an incrementing number to index the release candidate. there's nothing wrong with having the `x.y.z` and `x.y.z-rcN` tags point at the same commit, either.

**Comment by brianlheim** [comment]
feel free to close this whenever you'd like!

**Comment by madskjeldgaard** [comment]
I think I did this correctly on the latest release. Thanks :)
