### ISSUE TITLE
AUR package cannot be installed using some aur helpers

### ISSUE THREAD

**Issue by loopier** [madskjeldgaard/mkplugins#18]
Hi,  great plugins!

I installed them a few weeks ago on my Manjaro system (kernel Linux 5.10.26-1) and worked great.  But with the last major system upgrade, the package validity check now seems to fail.  Here's the output to `pamac update`:
```
==> Making package: supercollider-mkplugins 0.2.0-1 (Wed Apr 14 12:55:12 2021)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found MKPlugins-Linux.zip
==> Validating source files with md5sums...
    MKPlugins-Linux.zip ... FAILED
==> ERROR: One or more files did not pass the validity check!
Error: Failed to build supercollider-mkplugins
```

Just reckoned I should report it in case you weren't already aware of this.

Cheers!

**Comment by madskjeldgaard** [comment]
Thanks! There must be something wrong with my checksums then... I'll try and fix it asap

**Comment by madskjeldgaard** [comment]
Could you try updating/installing again? I think I may have found the bug now

**Comment by loopier** [comment]
Doesn't seem to be solved.  I refreshed the databases just in case, but got this:

**Comment by madskjeldgaard** [comment]
Thanks. Which aur helper are you using? For some reason, this does not happen on Yay but seen it with others

**Comment by loopier** [comment]
I'm using pamac-manager with AUR activated.

**Comment by madskjeldgaard** [comment]
Thanks. I'll investigate further. This also happens on PARU. 

If you get impatient, you can downloade the pkgbuild from here https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=supercollider-mkplugins
put it in a new directory and run `makepkg -si --clean` to manually install it like this. 

Although, hopefully I will solve this soon.

**Comment by loopier** [comment]
Thanks!  But I can wait :)

**Comment by madskjeldgaard** [comment]
I think I've solved it now! Could you try again? Thanks for the help

**Comment by loopier** [comment]
It's fixed!

**Comment by madskjeldgaard** [comment]
Woohoo. That's great! Thanks for the report
