### ISSUE TITLE
Merge into sc3-plugins

### ISSUE THREAD

**Issue by fmiramar** [madskjeldgaard/mkplugins#19]
Hi! 

Thanks for this repo, excelent materials! 

Are you thinking about merging it into the main sc3-plugins repo ? It would be great for beginners to have it there!

**Comment by madskjeldgaard** [comment]
Hi @fmiramar ! 

Thanks ! 

I don't have plans for doing that at the moment but the idea has crossed my mind. I find it a little bit easier to maintain it in it's own repo for now, but sometime down the line it could be an idea to merge it in there. 

That said, I've done almost everything I can to make it beginner friendly here with prebuilt releases that you download and extract and then they should work without having to compile anything (see here for latest prebuilt release https://github.com/madskjeldgaard/mkplugins/releases/tag/v0.2.3). 

If you see anything here that could be more beginner friendly feel free to let me know via an issue here or a pull request. 

Best!

**Comment by fmiramar** [comment]
Thanks! 

I will create a feature request there to see if someone is able to keep merging your releases there. BTW I am curious about how does the sc3-plugins workflow works, especially about incorporating new plugins. 

The problem that I am facing with multiple repos it is because when you are remotely colaborating with instrumentalists that does not have strong computer skills it is really hard for them to install SC and plugins which are spread over repos. Shipping a standalone would be the solution, but it is only available for MAC...
