### ISSUE TITLE
CMake error

### ISSUE THREAD

**Issue by igormpc** [madskjeldgaard/mkplugins#2]
hi mads
I got a Cmake error trying to install mkplugins today:

[igor@v410 build]$ cmake .. -DCMAKE_BUILD_TYPE='Release' -DSC_PATH=/home/igor/code/SuperCollider/ -DCMAKE_INSTALL_PREFIX=/home/igor/.local/share/SuperCollider/Extensions/
CMake Error: The source directory "/home/igor/code/mkplugins" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by madskjeldgaard** [comment]
Hi Igor. Thanks for the report. What commands did you run before CMake and what OS?

**Comment by igormpc** [comment]
thx mads -- i installed this dir 2 days ago, was working ok here on sc (Chen help tested).
i deleted the git cloned mkplugins dir today and re-run same lines before:
git clone https://github.com/madskjeldgaard/mkplugins
cd mkplugins
mkdir build
cd build
[igor@v410 build]$ cmake .. -DCMAKE_BUILD_TYPE='Release' -DSC_PATH=/home/igor/code/SuperCollider/ -DCMAKE_INSTALL_PREFIX=/home/igor/.local/share/SuperCollider/Extensions/
CMake Error: The source directory "/home/igor/code/mkplugins" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

I am on Arch Linux --
[igor@v410 ~]$ uname -a
Linux v410 5.10.16-arch1-1 #1 SMP PREEMPT Sat, 13 Feb 2021 20:50:18 +0000 x86_64 GNU/Linux

**Comment by madskjeldgaard** [comment]
Ahaha, my bad. Sorry, I accidentally deleted the CmakeLists.txt file on last upload. BRB

**Comment by madskjeldgaard** [comment]
Thanks for pointing out - should be fixed now.
