### ISSUE TITLE
DCompressor printing 0.0000 to post window

### ISSUE THREAD

**Issue by cdbzb** [madskjeldgaard/mkplugins#4]
Hi Mads *THANK YOU FOR THESE* !

here on mac Dcompressor is flooding the post window with 0.00000 

also help for DCompressor wont display (using scnvim -> pandoc)  I get:

ERROR: In /Users/michael/tank/super/Extensions/MKPlugins/HelpSource/Classes/DCompressor.schelp:
  At line 46: syntax error, unexpected end of file

**Comment by madskjeldgaard** [comment]
Thanks for the report ! I will check this out.

**Comment by madskjeldgaard** [comment]
This is now fixed in https://github.com/madskjeldgaard/mkplugins/releases/tag/v.0.1.5. Thanks for the report!
