### ISSUE TITLE
validity check error

### ISSUE THREAD

**Issue by igormpc** [madskjeldgaard/mkplugins#7]
hi mads
i got a validity check error trying to update mkplugins --

[igor@v410 code]$ yay -S supercollider-mkplugins
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:1]  supercollider-mkplugins-0.1.7D-1

  1 supercollider-mkplugins          (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> a
:: Deleting (1/1): /home/igor/.cache/yay/supercollider-mkplugins
:: Downloaded PKGBUILD (1/1): supercollider-mkplugins
  1 supercollider-mkplugins          (Installed) (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
:: (1/1) Parsing SRCINFO: supercollider-mkplugins
==> Making package: supercollider-mkplugins 0.1.7D-1 (Tue 23 Mar 2021 08:25:41 PM -03)
==> Retrieving sources...
  -> Downloading MKPlugins-Linux.zip...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   627  100   627    0     0    996      0 --:--:-- --:--:-- --:--:--   996
100  230k  100  230k    0     0   238k      0 --:--:-- --:--:-- --:--:-- 8388k
==> Validating source files with md5sums...
    MKPlugins-Linux.zip ... FAILED
==> ERROR: One or more files did not pass the validity check!
error downloading sources: supercollider-mkplugins

**Comment by madskjeldgaard** [comment]
Hi Igor. Sorry - I screwed up the checksums last night. Could you try again? I just updated it. Thanks
