### ISSUE TITLE
Server 'localhost' exited with exit code 0.

### ISSUE THREAD

**Issue by geoffroymontel** [madskjeldgaard/mkplugins#8]
Hello

Thanks for these wonderful plugins !

[scsynth_2021-03-24-103722_MacBook-Air-de-Geoffroy.crash.zip](https://github.com/madskjeldgaard/mkplugins/files/6195965/scsynth_2021-03-24-103722_MacBook-Air-de-Geoffroy.crash.zip)

On my Macbook Air running 10.14.6 and SC 3.11.2, I am getting 
```
Server 'localhost' exited with exit code 0.
```
when booting the server, say half of the time, when the MKPlugins (V0.1.7D) are installed.

I am attaching the crash log if it can help.

All the best

Geoffroy

**Comment by madskjeldgaard** [comment]
Oh wow that's nasty. Thanks for the report - I'll look into it.

**Comment by madskjeldgaard** [comment]
Did this happen with v.0.1.6 as well?

**Comment by geoffroymontel** [comment]
Yes, I was waiting for another version to report it ;)

**Comment by geoffroymontel** [comment]
Here is another crash log where I removed sc3plugins and VSTPlugin to let only MKPlugins, hope it helps
[scsynth_2021-03-24-110115_MacBook-Air-de-Geoffroy.crash.zip](https://github.com/madskjeldgaard/mkplugins/files/6196098/scsynth_2021-03-24-110115_MacBook-Air-de-Geoffroy.crash.zip)

**Comment by madskjeldgaard** [comment]
Thanks  a lot geoffroy! what was the last version you could get working? Thanks for the help!

**Comment by geoffroymontel** [comment]
Sorry @madskjeldgaard it looks like I'm getting the same crash log from time to time without any plugin.
Must be something with SC 3.11.2.
Closing this right now !

**Comment by madskjeldgaard** [comment]
> Sorry @madskjeldgaard it looks like I'm getting the same crash log from time to time without any plugin.
> Must be something with SC 3.11.2.
> Closing this right now !

Sorry to hear :( Let me know how it goes and feel free to reopen if it's got something to do with these plugins
